---
name: Negación y cuantificación
locale: es
type: learning
beta: false
teacher_info: "La intención de esta guía es introducir `forall` y `not` sin caer aún
  en consultas existenciales. \n\nY además, profundizar las ideas de individuos, valores,
  inferencia y reducción. "
language: prolog
id_format: '%05d'
order:
- 1
- 3
- 4
- 16
- 5
- 6
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 17
